style                          = "yas"
margin                         = 200
align_assignment               = true
align_conditional              = true
align_matrix                   = true
align_pair_arrow               = true
align_struct_field             = true
always_for_in                  = false
always_use_return              = false
remove_extra_newlines          = false
separate_kwargs_with_semicolon = false
trailing_comma                 = false
whitespace_in_kwargs           = true
whitespace_ops_in_indices      = true
whitespace_typedefs            = true
